name: 3. Deploy Application

on:
  push:
    branches: [main]
    paths: ['backend/**', 'frontend/**']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get App Service Names from Terraform State
        id: tf-outputs
        run: |
          cd infrastructure
          terraform init
          echo "backend_name=$(terraform output -raw backend_app_service_name)" >> $GITHUB_OUTPUT
          echo "frontend_name=$(terraform output -raw frontend_app_service_name)" >> $GITHUB_OUTPUT
          cd ..

      - name: Get Backend Publish Profile
        id: backend-profile
        run: |
          echo "profile=$(az webapp deployment list-publishing-profiles --name ${{ steps.tf-outputs.outputs.backend_name }} --resource-group $(az group list --query "[?starts_with(name, 'rg-auctionapp')].name" -o tsv) --xml)" >> $GITHUB_OUTPUT

      - name: Get Frontend Publish Profile
        id: frontend-profile
        run: |
          echo "profile=$(az webapp deployment list-publishing-profiles --name ${{ steps.tf-outputs.outputs.frontend_name }} --resource-group $(az group list --query "[?starts_with(name, 'rg-auctionapp')].name" -o tsv) --xml)" >> $GITHUB_OUTPUT

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Publish Backend
        run: dotnet publish backend/src/AuctionApp.Api/AuctionApp.Api.csproj -c Release -o ./publish-backend
      - name: Deploy Backend to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ steps.tf-outputs.outputs.backend_name }}
          publish-profile: ${{ steps.backend-profile.outputs.profile }}
          package: './publish-backend'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build
      - name: Deploy Frontend to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ steps.tf-outputs.outputs.frontend_name }}
          publish-profile: ${{ steps.frontend-profile.outputs.profile }}
          package: './frontend/build'