name: 3. Generate Class Diagram

on:
  push:
    branches: [main]
    paths: ['backend/src/AuctionApp.Api/Models/**']
  workflow_dispatch:

jobs:
  generate-class-diagram:
    name: Generate Class Diagram
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create docs directory
        run: mkdir -p docs

      - name: Generate and Commit Class Diagram
        uses: holothuroid/plantuml-github-action@main
        with:
          args: "-o ../../docs/ backend/src/AuctionApp.Api/Models"
        
      - name: Commit and Push Diagram
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add docs/class_diagram.png
          git commit -m "docs: Update class diagram" || echo "No changes to commit"
          git push